# Generated by Django 5.2.8 on 2025-11-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='Student', max_length=50)),
                ('department', models.CharField(max_length=100, null=True)),
                ('date_joined', models.DateField()),
                ('first_sign_up', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LearningStyleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_score', models.IntegerField()),
                ('reflective_score', models.IntegerField()),
                ('sensing_score', models.IntegerField()),
                ('intuitive_score', models.IntegerField()),
                ('visual_score', models.IntegerField()),
                ('verbal_score', models.IntegerField()),
                ('sequential_score', models.IntegerField()),
                ('global_score', models.IntegerField()),
                ('updated_at', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ILSResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('answer', models.CharField(choices=[('a', 'A'), ('b', 'B')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_style_type', models.CharField(choices=[('active', 'Active'), ('reflective', 'Reflective'), ('sensing', 'Sensing'), ('intuitive', 'Intuitive'), ('visual', 'Visual'), ('verbal', 'Verbal'), ('sequential', 'Sequential'), ('global', 'Global')], max_length=50)),
                ('duration_seconds', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('score', models.IntegerField()),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.contentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
