# Generated by Django 5.2.8 on 2025-12-07 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilsresponse',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='ilsresponse',
            name='question_number',
        ),
        migrations.AddField(
            model_name='ilsresponse',
            name='answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ilsresponse',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='learningstylescore',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
