# Generated by Django 5.2.8 on 2025-11-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF Document'), ('article', 'Article / Text Content'), ('audio', 'Audio'), ('image', 'Image'), ('presentation', 'PowerPoint / Slides'), ('link', 'External Link'), ('file', 'Other File'), ('quiz', 'Quiz')], max_length=50)),
                ('data', models.TextField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, max_length=255, null=True)),
                ('learning_style_type', models.CharField(choices=[('active', 'Active'), ('reflective', 'Reflective'), ('sensing', 'Sensing'), ('intuitive', 'Intuitive'), ('visual', 'Visual'), ('verbal', 'Verbal'), ('sequential', 'Sequential'), ('global', 'Global')], max_length=50)),
                ('difficulty_level', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_option', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=10)),
            ],
        ),
    ]
